function getQueryParam(t){let e=new URLSearchParams(window.location.search);return e.get(t)}async function fetchProductData(t){try{let e=await fetch("./products.json");if(!e.ok)throw Error(`HTTP error! status: ${e.status}`);let i=await e.json();return i.find(e=>e.id===t)}catch(r){console.error("Error fetching product data:",r)}}function displayProductData(t){if(!t){console.error("Product not found");return}document.querySelector(".image-preview img").src=t.image,document.querySelector(".details .title").textContent=t.title,document.querySelector(".details .price").textContent=`${t.price} L.E`;let e=document.querySelector(".details .rating");e.innerHTML="";let i=parseFloat(t.rating),r=Math.floor(i);for(let a=0;a<r;a++){let l=document.createElement("i");l.classList.add("fa-solid","fa-star","active-rate"),e.appendChild(l)}if(i%1!=0){let s=document.createElement("i");s.classList.add("fa-solid","fa-star-half","active-rate"),e.appendChild(s)}for(let c=0;c<5-Math.ceil(i);c++){let n=document.createElement("i");n.classList.add("fa-solid","fa-star"),e.appendChild(n)}let d=document.querySelector(".details .colors");d.innerHTML="",t.colors.forEach(t=>{let e=document.createElement("div");e.classList.add(t.toLowerCase()),d.appendChild(e)})}document.addEventListener("DOMContentLoaded",async()=>{let t=getQueryParam("id");if(!t){console.error("No product ID found in URL");return}let e=await fetchProductData(t);displayProductData(e)}),document.addEventListener("DOMContentLoaded",async()=>{let t=getQueryParam("id");if(!t){console.error("No product ID found in URL");return}let e=await fetchProductData(t);displayProductData(e);let i=document.querySelectorAll(".add-to-cart"),r=document.querySelectorAll(".wishlist");function a(t){let e=JSON.parse(localStorage.getItem("cart"))||[];e.push(t),localStorage.setItem("cart",JSON.stringify(e)),s(e)}function l(t,e){let i=JSON.parse(localStorage.getItem("wishlist"))||[],r=i.findIndex(e=>e.id===t.id);-1!==r?(i.splice(r,1),e.classList.remove("liked")):(i.push(t),e.classList.add("liked")),localStorage.setItem("wishlist",JSON.stringify(i)),c(i)}function s(t){let e=document.getElementById("cart-items");e.innerHTML=t.map(t=>`
        <div class="cart-item">
          <img src="${t.img}" alt="${t.title}">
          <div class="cart-item-details">
            <p>${t.title}</p>
            <p>${t.price}</p>
          </div>
          <span class="remove" data-id="${t.id}">&times;</span>
        </div>
      `).join(""),document.querySelectorAll(".cart-item .remove").forEach(t=>{t.addEventListener("click",t=>n(t.target.dataset.id))})}function c(t){let e=document.getElementById("wishlist-subset");e.innerHTML=t.map(t=>`
        <div class="wishlist-item">
          <img src="${t.img}" alt="${t.title}">
          <p>${t.title}</p>
          <span class="remove" data-id="${t.id}">&times;</span>
        </div>
      `).join(""),document.querySelectorAll(".wishlist-item .remove").forEach(t=>{t.addEventListener("click",t=>d(t.target.dataset.id))})}function n(t){let e=JSON.parse(localStorage.getItem("cart"))||[];e=e.filter(e=>e.id!==t),localStorage.setItem("cart",JSON.stringify(e)),s(e)}function d(t){let e=JSON.parse(localStorage.getItem("wishlist"))||[];e=e.filter(e=>e.id!==t),localStorage.setItem("wishlist",JSON.stringify(e)),c(e)}i.forEach(e=>{e.addEventListener("click",()=>{let i=e.closest(".product-info"),r={id:t,title:i.querySelector(".title").textContent,img:i.querySelector(".image-preview img").src,price:i.querySelector(".price").textContent};a(r)})}),r.forEach(e=>{e.addEventListener("click",()=>{let i=e.closest(".product-info"),r={id:t,title:i.querySelector(".title").textContent,img:i.querySelector(".image-preview img").src,price:i.querySelector(".price").textContent};l(r,e)})})});