function getQueryParam(e){return new URLSearchParams(window.location.search).get(e)}async function fetchProductData(e){try{let t=await fetch("./products.json");if(!t.ok)throw Error(`HTTP error! status: ${t.status}`);return(await t.json()).find(t=>t.id===e)}catch(i){console.error("Error fetching product data:",i)}}function displayProductData(e){if(!e){console.error("Product not found");return}document.querySelector(".image-preview img").src=e.image,document.querySelector(".details .title").textContent=e.title,document.querySelector(".details .price").textContent=`${e.price} L.E`;let t=document.querySelector(".details .rating");t.innerHTML="";let i=parseFloat(e.rating),r=Math.floor(i);for(let a=0;a<r;a++){let s=document.createElement("i");s.classList.add("fa-solid","fa-star","active-rate"),t.appendChild(s)}if(i%1!=0){let n=document.createElement("i");n.classList.add("fa-solid","fa-star-half","active-rate"),t.appendChild(n)}for(let l=0;l<5-Math.ceil(i);l++){let o=document.createElement("i");o.classList.add("fa-solid","fa-star"),t.appendChild(o)}let d=document.createElement("span");d.textContent=` (${e.ratingCount})`,t.appendChild(d),document.querySelector(".dimensions .width").textContent=e.dimensions.width,document.querySelector(".dimensions .height").textContent=e.dimensions.height,document.querySelector(".dimensions .depth").textContent=e.dimensions.depth;let c=document.querySelector(".details .colors");c.innerHTML="",e.colors.forEach(e=>{let t=document.createElement("div");t.classList.add(e.toLowerCase()),c.appendChild(t)})}function showMoreProducts(){let e=document.querySelectorAll(".product-item.hidden");e.forEach(e=>{e.classList.remove("hidden")});let t=document.getElementById("show-more-products");t.style.display="none",document.getElementById("view-more-suggest").style.display="none"}document.addEventListener("DOMContentLoaded",async()=>{let e=getQueryParam("id");if(!e){console.error("No product ID found in URL");return}displayProductData(await fetchProductData(e))}),document.addEventListener("DOMContentLoaded",async()=>{let e=getQueryParam("id");if(!e){console.error("No product ID found in URL");return}displayProductData(await fetchProductData(e));let t=document.querySelectorAll(".add-to-cart"),i=document.querySelectorAll(".wishlist");function r(e){let t=JSON.parse(localStorage.getItem("cart"))||[];t.push(e),localStorage.setItem("cart",JSON.stringify(t)),s(t)}function a(e,t){let i=JSON.parse(localStorage.getItem("wishlist"))||[],r=i.findIndex(t=>t.id===e.id);-1!==r?(i.splice(r,1),t.classList.remove("liked")):(i.push(e),t.classList.add("liked")),localStorage.setItem("wishlist",JSON.stringify(i)),n(i)}function s(e){document.getElementById("cart-items").innerHTML=e.map(e=>`
      <div class="cart-item">
        <img src="${e.img}" alt="${e.title}">
        <div class="cart-item-details">
          <p>${e.title}</p>
          <p>${e.price}</p>
        </div>
        <span class="remove" data-id="${e.id}">&times;</span>
      </div>
    `).join(""),document.querySelectorAll(".cart-item .remove").forEach(e=>{e.addEventListener("click",e=>l(e.target.dataset.id))})}function n(e){document.getElementById("wishlist-subset").innerHTML=e.map(e=>`
      <div class="wishlist-item">
        <img src="${e.img}" alt="${e.title}">
        <p>${e.title}</p>
        <span class="remove" data-id="${e.id}">&times;</span>
      </div>
    `).join(""),document.querySelectorAll(".wishlist-item .remove").forEach(e=>{e.addEventListener("click",e=>o(e.target.dataset.id))})}function l(e){let t=JSON.parse(localStorage.getItem("cart"))||[];t=t.filter(t=>t.id!==e),localStorage.setItem("cart",JSON.stringify(t)),s(t)}function o(e){let t=JSON.parse(localStorage.getItem("wishlist"))||[];t=t.filter(t=>t.id!==e),localStorage.setItem("wishlist",JSON.stringify(t)),n(t)}t.forEach(t=>{t.addEventListener("click",()=>{let i=t.closest(".product-info");r({id:e,title:i.querySelector(".title").textContent,img:i.querySelector(".image-preview img").src,price:i.querySelector(".price").textContent})})}),i.forEach(t=>{t.addEventListener("click",()=>{let i=t.closest(".product-info");a({id:e,title:i.querySelector(".title").textContent,img:i.querySelector(".image-preview img").src,price:i.querySelector(".price").textContent},t)})})});
